name: hola-mundo #Nombre del workflow
on: #Event through push
  push:
    branches: ["coursera-github-actions"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: configure node.js
        uses: actions/setup-node@v6
        with:
          node-version: '24'

      - name: execute script
        run: node hola_mundo.js
      
